#!/usr/bin/env php
<?php
/**
 *    Porter CLI implementation
 */
use Infernusophiuchus\Porter\Main;
use Infernusophiuchus\Porter\Exceptions\MainException;

require_once __DIR__.'/porter-autoload.php';

try {

    new Main(
        __DIR__,
        __DIR__.'/dev/dist',
        __DIR__,
        (string)$argv[1]
    );

} catch (MainException $e) {

    echo "\nERROR, ".$e->getCode().": ".$e->getMessage()."\n";

}
